import Link from 'next/link'
import { PageShell } from '@/components/layout/PageShell'
import { GuideCards } from '@/page/guides/GuideCards'
import { HomeHero } from '@/page/home/HomeHero'
import { getGuides } from '@/lib/data/content'
import { localizePath } from '@/lib/locale'
import { translate } from '@/lib/translations'
import type { Locale } from '@/types/content'

const plannedFeatures = ['multiplayer', 'environment', 'ai', 'inventory', 'world', 'usable', 'fortification', 'survivalism', 'characters', 'trade', 'vehicles', 'grid']
const reviews = [
  ['X', 'XxBoyEatsGirlxX', '"This review is counted in the overall review score because this user purchased the game directly on Steam or got a free license of a free game\nRecommended\n71.4 hrs on record (55.2 hrs at review time)\nEarly Access Review\nPosted: 15 November\nI am a 7 Days to Die fanatic. Absolutely love that game but have watched as the game missed the mark with updates, patches and DLC.\nVein is THE BEST zombie survival game I have played. Period.\nA cross of seven days and proj Z in first person. The jaw dropping amount of content these 2 developers have put into this game is astounding. And their road map and constant updates lets me know these devs love their baby!\nI\'m not sure I need to play any other game than this one.\nVein is a beautiful well crafted world that is only going to get better!"'],
  ['C', 'Cole', '"Ill start of by saying that this is going to be the next great zombie survival game. The realism is incredible. What you expect to happen in real life, happens in the game so it makes survival feel real. The fact you can search and demolish just about anything is a huge bright spot. I can already picture the multiplayer servers where a clan has control of the prison (like in the walking dead) while having parts of their team exploring and negotiating with other settlements that maybe control and entire town (yes its possible)"'],
  ['M', 'Mariner', '"World interactivity in VEIN game is wild—being able to open anything, move anything, and weaponize junk makes this survival game feel alive."'],
  ['R', 'Refgain', '"Great game. These devs kicks ass compared to sucky EA or any other multi million company!!!!"'],
  ['R', 'reznov', '"absolute banger of a game. It\'s rusty, a bit buggy on the edges but it\'s new and being worked on; Even then, I love it, been playing for a while and I\'m excited to keep doing so and see how the game grows. Keep it up, people."'],
  ['A', 'Archive', '"Excellent game. The POIs are very good. The ability to continually expand is excellent. However, killing animals does not yield enough. If the animal was infected or diseased, understandable. Looking forward to the next update."'],
]

export function HomePage({ locale }: { locale: Locale }) {
  const t = (key: string, fallback?: string) => translate(locale, key, fallback)
  const guides = getGuides(locale).slice(0, 9)
  return <PageShell locale={locale}><div className="home-view"><main><HomeHero locale={locale} />
    <section className="what-is"><div className="container"><h2 className="section-title">{t('homePage.whatIs.title')}</h2><p className="section-subtitle">{t('homePage.whatIs.subtitle')}</p>
      <div className="what-is-content"><div className="what-is-image"><img src="/images/what-01.webp" alt="VEIN Game" /></div><div className="what-is-text"><h3>{t('homePage.whatIs.scavenging.title')}</h3><p>{t('homePage.whatIs.scavenging.content1')} <Link href={localizePath(locale, '/vein-guides/vein-best-loot-locations')} className="inline-link">{t('homePage.whatIs.scavenging.link1')}</Link> {t('homePage.whatIs.scavenging.content2')}</p><p>{t('homePage.whatIs.scavenging.content3')} <Link href={localizePath(locale, '/vein-wiki/controls')} className="inline-link">{t('homePage.whatIs.scavenging.link2')}</Link> {t('homePage.whatIs.scavenging.content4')}</p></div></div>
      <div className="what-is-content reverse"><div className="what-is-image"><img src="/images/what-02.webp" alt="VEIN Game" /></div><div className="what-is-text"><h3>{t('homePage.whatIs.dynamic.title')}</h3><p>{t('homePage.whatIs.dynamic.content1')} <Link href={localizePath(locale, '/vein-wiki/mechanics')} className="inline-link">{t('homePage.whatIs.dynamic.link1')}</Link> {t('homePage.whatIs.dynamic.content2')}</p><p>{t('homePage.whatIs.dynamic.content3')}</p></div></div>
      <div className="what-is-content"><div className="what-is-image"><img src="/images/what-03.webp" alt="VEIN Game" /></div><div className="what-is-text"><h3>{t('homePage.whatIs.defending.title')}</h3><p>{t('homePage.whatIs.defending.content1')} <Link href={localizePath(locale, '/vein-guides/vein-best-base-location-survival-guide')} className="inline-link">{t('homePage.whatIs.defending.link1')}</Link> {t('homePage.whatIs.defending.content2')} <Link href={localizePath(locale, '/vein-wiki/building')} className="inline-link">{t('homePage.whatIs.defending.link2')}</Link> {t('homePage.whatIs.defending.content3')} <Link href={localizePath(locale, '/vein-guides/vein-game-how-to-power-street-light')} className="inline-link">{t('homePage.whatIs.defending.link4')}</Link> {t('homePage.whatIs.defending.content6')}</p><p>{t('homePage.whatIs.defending.content4')} <Link href={localizePath(locale, '/vein-wiki/skills')} className="inline-link">{t('homePage.whatIs.defending.link3')}</Link> {t('homePage.whatIs.defending.content5')}</p></div></div>
    </div></section>
    <section className="guides-section"><div className="container"><h2 className="section-title">{t('homePage.guides.title')}</h2><p className="section-subtitle">{t('homePage.guides.subtitle')}</p><GuideCards guides={guides} locale={locale} showCategory={false} viewLink={t('homePage.guides.viewLink')} /><div className="guides-actions"><Link href={localizePath(locale, '/vein-guides')} className="btn-hero btn-secondary">{t('homePage.guides.viewAll')}</Link></div></div></section>
    <section className="map-section"><div className="container"><h2 className="section-title">{t('homePage.map.title')}</h2><p className="section-subtitle">{t('homePage.map.subtitle')}</p><div className="map-card"><div className="map-card-content"><h3>{t('homePage.map.card.title')}</h3><p>{t('homePage.map.card.description')}</p><ul className="map-features">{['zoom', 'poi', 'towns', 'realTime'].map((feature) => <li key={feature}>{t(`homePage.map.features.${feature}`)}</li>)}</ul><div className="map-actions"><Link href={localizePath(locale, '/vein-map-detail')} className="btn-hero btn-steam">{t('homePage.map.button')}</Link><Link href={localizePath(locale, '/vein-map')} className="btn-hero btn-secondary">{t('homePage.map.button2')}</Link></div></div><div className="map-card-image"><div className="map-preview"><img src="/images/map-img.webp" alt="VEIN Interactive Map" loading="lazy" /></div></div></div></div></section>
    <section className="game-info"><div className="container"><h2 className="section-title">{t('homePage.gameInfo.title')}</h2><p className="section-subtitle">{t('homePage.gameInfo.subtitle')}</p><div className="info-layout"><div className="info-card"><h3>{t('homePage.gameInfo.snapshot.title')}</h3><ul>{['title', 'developer', 'release', 'platform', 'modes', 'contentAdvisory'].map((field) => <li key={field}><span>{t(`homePage.gameInfo.snapshot.fields.${field}`)}</span><span>{t(`homePage.gameInfo.snapshot.fields.${field}Value`)}</span></li>)}</ul></div><div className="info-card"><h3>{t('homePage.gameInfo.requirements.title')}</h3><div className="requirements">{(['minimum', 'recommended'] as const).map((level) => <div key={level}><p className="req-label">{t(`homePage.gameInfo.requirements.${level}`)}</p><ul>{(level === 'minimum' ? ['os', 'memory', 'directx', 'storage'] : ['os', 'memory', 'directx', 'network', 'storage']).map((item) => <li key={item}>{t(`homePage.gameInfo.requirements.${level}Items.${item}`)}</li>)}</ul></div>)}</div></div></div><div className="language-table"><table><thead><tr>{['language', 'interface', 'audio', 'subtitles'].map((header) => <th key={header}>{t(`homePage.gameInfo.language.table.${header}`)}</th>)}</tr></thead><tbody><tr><td>{t('homePage.gameInfo.language.table.english')}</td><td>✓</td><td /><td>✓</td></tr><tr><td>{t('homePage.gameInfo.language.table.additional')}</td><td colSpan={3}>{t('homePage.gameInfo.language.table.additionalValue')}</td></tr></tbody></table></div></div></section>
    <section className="planned-section"><div className="container"><h2 className="section-title">{t('homePage.planned.title')}</h2><p className="section-subtitle">{t('homePage.planned.subtitle')}</p><div className="planned-grid">{plannedFeatures.map((feature) => <article className="planned-card" key={feature}><h3>{t(`homePage.planned.features.${feature}.title`)}</h3><p>{t(`homePage.planned.features.${feature}.description`)}</p></article>)}</div></div></section>
    <section className="reviews-section"><div className="container"><h2 className="section-title">{t('homePage.reviews.title')}</h2><p className="section-subtitle">{t('homePage.reviews.subtitle')}</p><div className="reviews-grid">{reviews.map(([initial, name, review]) => <article className="review-card" key={name}><div className="reviewer"><span className="avatar">{initial}</span><div><h4>{name}</h4><p>★★★★★</p></div></div><p>{review}</p></article>)}</div></div></section>
    <section className="faq-section"><div className="container"><h2 className="section-title">{t('homePage.faq.title')}</h2><div className="faq-grid">{['whatIs', 'platforms', 'languages', 'demo', 'content', 'updates'].map((item) => <article className="faq-item" key={item}><h3>{t(`homePage.faq.items.${item}.question`)}</h3><p>{t(`homePage.faq.items.${item}.answer`)}</p></article>)}<article className="faq-item"><h3>{t('homePage.faq.items.different.question')}</h3><p>{t('homePage.faq.items.different.answer1')} <Link href={localizePath(locale, '/vein-wiki/mechanics')} className="inline-link">{t('homePage.faq.items.different.link')}</Link> {t('homePage.faq.items.different.answer2')}</p></article><article className="faq-item"><h3>{t('homePage.faq.items.multiplayer.question')}</h3><p>{t('homePage.faq.items.multiplayer.answer1')} <Link href={localizePath(locale, '/vein-guides')} className="inline-link">{t('homePage.faq.items.multiplayer.link')}</Link>{t('homePage.faq.items.multiplayer.answer2')}</p></article></div></div></section>
    <section className="cta-section"><div className="container"><div className="cta-content"><h2>Join VEIN survival game network today</h2><p>Add VEIN game to your wishlist or download the free demo to learn VEIN survival game mechanics, stock your hideout, and rally friends before Early Access begins. The demo lets you experience the core gameplay of this post-apocalyptic survival multiplayer sandbox game, with access to a small region and skill progression up to level 50. Discover why VEIN game is one of the most anticipated survival games of 2025.</p><p>Early Access launches October 24, 2025, bringing the full VEIN survival game experience. Join the community and help shape the future of VEIN game through your feedback during Early Access. VEIN survival game continues to evolve based on player input, making your voice important in the development of VEIN game.</p><div className="cta-actions"><a href="https://store.steampowered.com/app/1857950/VEIN/" className="btn-hero btn-steam" target="_blank" rel="noreferrer nofollow">Get Early Access</a><a href="https://vein.gg/" className="btn-hero btn-secondary" target="_blank" rel="noreferrer nofollow">Follow Official Site</a></div></div></div></section>
  </main></div></PageShell>
}
