import Link from 'next/link'
import { PageShell } from '@/components/layout/PageShell'
import { getItems, itemCategories, type ItemCategory } from '@/lib/data/content'
import { localizePath } from '@/lib/locale'
import { translate } from '@/lib/translations'
import type { Locale } from '@/types/content'

const descriptions: Record<ItemCategory, string> = {
  weapons: 'All weapons available in VEIN game, including melee and ranged weapons.', armor: 'Protective gear that keeps survivors alive when raids turn deadly.', clothing: 'Outfits and tactical apparel that provide comfort and concealment.', consumables: 'Food, drinks, and temporary buffs that keep you moving.', special: 'Unique items, limited drops, and rare rewards from events.', materials: 'Crafting components used to build, upgrade, and repair equipment.', ammo: 'Ammunition types for every weapon platform in VEIN game.', medical: 'Medkits, bandages, and pharmaceuticals to keep squads alive.', tools: 'Utility tools for construction, exploration, and survival tasks.', misc: 'Everything else: quest items, trade goods, and collectibles.',
}

export function ItemsPage({ locale }: { locale: Locale }) {
  return <PageShell locale={locale}><div className="items-view"><div className="container"><div className="page-header"><h1 className="page-title">{translate(locale, 'itemsPage.header.title')}</h1><p className="page-subtitle">{translate(locale, 'itemsPage.header.subtitle')}</p></div><h2 className="section-title">{translate(locale, 'itemsPage.allCategories')}</h2><div className="category-grid">{itemCategories.map((category) => <Link key={category} href={localizePath(locale, `/vein-items/${category}`)} className="category-card"><div className="card-top"><div className="card-title-wrap"><h3 className="card-title">{category}</h3><span className="item-count">{getItems(locale, category).length} items</span></div><p className="card-desc">{descriptions[category]}</p></div><div className="card-bottom"><span className="explore">{translate(locale, 'itemsPage.exploreCategory')}</span><span className="arrow">›</span></div></Link>)}</div></div><section className="why-choose-us-section"><div className="container"><h2 className="section-title">Why Choose Our VEIN Items Database?</h2><p className="section-subtitle">The most comprehensive and detailed item database for VEIN survival game, covering every weapon, tool, and resource.</p><div className="features-grid">{[['🗡️', 'Complete Weapon Database', 'Browse our extensive weapons collection with detailed stats including damage, DPS, weight, and special uses.'], ['🛡️', 'Armor & Protection Guide', 'Discover all protective gear in our armor database. Learn about helmets, body armor, and protective clothing.'], ['🔧', 'Tools & Crafting Materials', 'Master crafting and construction with our complete tools database and materials guide.'], ['💊', 'Medical & Survival Items', 'Keep your character alive with our medical items database.'], ['🍖', 'Consumables & Resources', 'Never go hungry with our consumables database and ammo guide.'], ['📊', 'Detailed Item Stats', 'Every item entry includes comprehensive information for strategic decisions.']].map(([icon, title, description]) => <article key={title} className="feature-card"><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section></div></PageShell>
}
